### ISSUE TITLE
Recommendation regarding documentation

### ISSUE THREAD

**Issue by Feilner** [HQJaTu/RDP-cert-tools#1]
Great tool! Just successful used it!

I would have been much faster when I knew to points so please add them to the readme.md!
1. Dependency to PSPKI module and how to install it `Install-Module -Name PSPKI` 
2. How to set script execution `Set-ExecutionPolicy Unrestricted -Scope CurrentUser` (The info is in the .ps1 file but not the readme.md()
3. RDP can't deal with certificate chains I have to use the plain cert and not the chain. Please add a note. (Actually I have no glue why RDP does not ask for the intermediate cert)

**Comment by HQJaTu** [comment]
Thank you for the feedback.

All of your points are worth documenting. I'll improve the docs per your suggestion with the mentioned content.

**Comment by HQJaTu** [comment]
Fixed in https://github.com/HQJaTu/RDP-cert-tools/commit/1b9a9bd279b6c19dace40c0510b757c0a3e17eb0.

Should further requirements covering this issue raise, please, re-open. For any new ones, file a new issue.
